# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'IkinariMemo' do

  pod 'RealmSwift'
  pod 'Google-Mobile-Ads-SDK'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IkinariMemo

  target 'IkinariMemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IkinariMemoUITests' do
    # Pods for testing
  end

end
